### ISSUE TITLE
Error: MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)

### ISSUE THREAD

**Issue by DevTiago** [akbarpulatov/flutter_map_picker#3]
Hello,

I've discover your package and im trying to get it working. I've copied the example and im getting this error when moving the map:

Error: MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)

Any ideia to fix it ?

**Comment by akbarpulatov** [comment]
Can you share the `pubspec.yaml` of your app?

**Comment by akbarpulatov** [comment]
This is the packages that example app uses:
```
  cupertino_icons:
  geocoding:
  google_maps_flutter: 
  flutter_svg: 
  map_picker:
```
Did you import them to your project?
